# Actividad 1 corte 2 IA II

* # EDA

In [54]:
# Importamos librerias necesarias

import pandas as pd

In [55]:
data = pd.read_excel("DataEnergy.xlsx") # Cargamos el dataset
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2020,2020,2020
1,NaN,NaN,NaN,NaN,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3
2,NaN,NaN,CUENTA CONTRATO,NaN,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes
3,NaN,ATM REMOTO,10001,NaN,159,145,119,145,137,136,122,143,121,144,131,126,114,117,129
4,NaN,ATM REMOTO,10002,NaN,734,145,423,424,521,545,485,558,464,519,476,463,446,460,451

In [56]:
data.info() # Info general, vemos que hay bastantes nulos

<class 'pandas.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   367 non-null    str
 2   Unnamed: 2   368 non-null    str
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   349 non-null    object
 5   Unnamed: 5   349 non-null    object
 6   Unnamed: 6   349 non-null    object
 7   Unnamed: 7   349 non-null    object
 8   Unnamed: 8   349 non-null    object
 9   Unnamed: 9   349 non-null    object
 10  Unnamed: 10  349 non-null    object
 11  Unnamed: 11  349 non-null    object
 12  Unnamed: 12  348 non-null    object
 13  Unnamed: 13  348 non-null    object
 14  Unnamed: 14  348 non-null    object
 15  Unnamed: 15  348 non-null    object
 16  Unnamed: 16  365 non-null    object
 17  Unnamed: 17  364 non-null    object
 18  Unnamed: 18  362 non-null    object
dtypes: float64(2), object(15), str(2)
memory usage: 55.1+ KB

In [57]:
data.isnull().sum() # Contamos los null

Unnamed: 0     370
Unnamed: 1       3
Unnamed: 2       2
Unnamed: 3     370
Unnamed: 4      21
Unnamed: 5      21
Unnamed: 6      21
Unnamed: 7      21
Unnamed: 8      21
Unnamed: 9      21
Unnamed: 10     21
Unnamed: 11     21
Unnamed: 12     22
Unnamed: 13     22
Unnamed: 14     22
Unnamed: 15     22
Unnamed: 16      5
Unnamed: 17      6
Unnamed: 18      8
dtype: int64

In [58]:
# Empezamos a limpiar el dataset

dataClean = data.drop(data.columns[[0,3]], axis=1) # Eliminamos las columnas 0 y 3 (1 y 4) las cuales están totalmente vacías
dataClean.head(10)

,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2020,2020,2020
1,NaN,NaN,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3
2,NaN,CUENTA CONTRATO,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes,CONSUMO kWh/mes
3,ATM REMOTO,10001,159,145,119,145,137,136,122,143,121,144,131,126,114,117,129
4,ATM REMOTO,10002,734,145,423,424,521,545,485,558,464,519,476,463,446,460,451
5,OFICINA,10003,4843,4917,4356,4862,4618,4878,5186,5067,4657,4218,3582,3455,3349,3414,2285
6,ATM REMOTO,10004,201,197,2285,2277,2330,2330,2549,2297,2389,2336.571429,2343.938776,2333.644315,246,0,492
7,ATM REMOTO,10005,130,152,0,0,0,0,0,0,0,0,0,0,160.5,0,321
8,ATM REMOTO,10006,402,520,3853,4338,3660,3660,3815,3738,3321,3624.857143,3592.265306,3649.588921,677,0,1354
9,ATM REMOTO,10007,201,197,1278,1260,1235,1235,1486,1093,565,1184.285714,1170.897959,1158.169096,130,0,260

In [59]:
# Vemos que la fila 1 y 2 son el año y mes las unimos para que quede en una solo fila y no tener multiples indices

new_cols = ['TIPO', 'CUENTA_CONTRATO'] # Nombres de la columna 1 y 2

for i in dataClean.columns[2:]: # Recorremos de la columna 3 en adelante
    anio = int(data[i].iloc[0])            # Obtiene el año de la fila 0
    mes = int(data[i].iloc[1])             # Obtiene el mes de la fila 1

    fecha_header = f"{anio}-{mes:02d}" # Formateamos anio + mes con cero a izquierda
    new_cols.append(fecha_header)

#print(new_cols)
dataClean.columns = new_cols # Asignamos los nuevos nombres de columna

dataClean = dataClean.iloc[3:].reset_index(drop=True) # Eliminamos las filas 0, 1 y 2 y reiniciamos el índice
# Sabemos que los numeros representan CONSUMO kWh/mes, por eso lo quitamos de los indices
dataClean.head()

,TIPO,CUENTA_CONTRATO,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,ATM REMOTO,10001,159,145,119,145,137,136,122,143,121,144,131,126,114,117,129
1,ATM REMOTO,10002,734,145,423,424,521,545,485,558,464,519,476,463,446,460,451
2,OFICINA,10003,4843,4917,4356,4862,4618,4878,5186,5067,4657,4218,3582,3455,3349,3414,2285
3,ATM REMOTO,10004,201,197,2285,2277,2330,2330,2549,2297,2389,2336.571429,2343.938776,2333.644315,246,0,492
4,ATM REMOTO,10005,130,152,0,0,0,0,0,0,0,0,0,0,160.5,0,321

In [60]:
# como vimos en dataClean.info() sabemos que los datos están en tipo object y los necesitamos en numeriicos

dataClean[cols_fechas] = dataClean[cols_fechas].apply(pd.to_numeric, errors='coerce') # convertimos los str a numericos
dataClean.head()

,TIPO,CUENTA_CONTRATO,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,ATM REMOTO,10001,159.0,145.0,119.0,145.0,137.0,136.0,122.0,143.0,121.0,144.000000,131.000000,126.000000,114.0,117.0,129.0
1,ATM REMOTO,10002,734.0,145.0,423.0,424.0,521.0,545.0,485.0,558.0,464.0,519.000000,476.000000,463.000000,446.0,460.0,451.0
2,OFICINA,10003,4843.0,4917.0,4356.0,4862.0,4618.0,4878.0,5186.0,5067.0,4657.0,4218.000000,3582.000000,3455.000000,3349.0,3414.0,2285.0
3,ATM REMOTO,10004,201.0,197.0,2285.0,2277.0,2330.0,2330.0,2549.0,2297.0,2389.0,2336.571429,2343.938776,2333.644315,246.0,0.0,492.0
4,ATM REMOTO,10005,130.0,152.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,160.5,0.0,321.0

In [61]:
dataClean.info()

<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TIPO             367 non-null    str
 1   CUENTA_CONTRATO  367 non-null    str
 2   2019-01          345 non-null    float64
 3   2019-02          346 non-null    float64
 4   2019-03          345 non-null    float64
 5   2019-04          346 non-null    float64
 6   2019-05          345 non-null    float64
 7   2019-06          346 non-null    float64
 8   2019-07          345 non-null    float64
 9   2019-08          346 non-null    float64
 10  2019-09          344 non-null    float64
 11  2019-10          345 non-null    float64
 12  2019-11          344 non-null    float64
 13  2019-12          345 non-null    float64
 14  2020-01          356 non-null    float64
 15  2020-02          355 non-null    float64
 16  2020-03          352 non-null    float64
dtypes: float64(15), str(2)
memory usage: 48.9 KB

In [62]:
dataClean.isnull().sum() # Vemos que todavia hay datos nulos

TIPO                0
CUENTA_CONTRATO     0
2019-01            22
2019-02            21
2019-03            22
2019-04            21
2019-05            22
2019-06            21
2019-07            22
2019-08            21
2019-09            23
2019-10            22
2019-11            23
2019-12            22
2020-01            11
2020-02            12
2020-03            15
dtype: int64

In [63]:
# Filtramos las filas donde TODOS los meses son nulos (excluyendo TIPO y CUENTA_CONTRATO)
cuentas_inactivas = dataClean[dataClean.drop(columns=['TIPO', 'CUENTA_CONTRATO']).isna().all(axis=1)]

print(f"Total de cuentas completamente vacías: {len(cuentas_inactivas)}")
print(cuentas_inactivas[['TIPO', 'CUENTA_CONTRATO']])

Total de cuentas completamente vacías: 5
           TIPO CUENTA_CONTRATO
17   ATM REMOTO           10018
19   ATM REMOTO           10020
25   ATM REMOTO           10026
26   ATM REMOTO           10027
315  ATM REMOTO           10316

In [64]:
# Eliminamos las filas por su índice y reiniciamos el índice de la tabla
dataClean = dataClean.drop(index=cuentas_inactivas.index).reset_index(drop=True)

In [65]:
dataClean.isnull().sum()

TIPO                0
CUENTA_CONTRATO     0
2019-01            17
2019-02            16
2019-03            17
2019-04            16
2019-05            17
2019-06            16
2019-07            17
2019-08            16
2019-09            18
2019-10            17
2019-11            18
2019-12            17
2020-01             6
2020-02             7
2020-03            10
dtype: int64